kind = "web"
previewPath = "/"
title = "StreamFlix"
version = "1.0.0"
id = "artifacts/streamflix"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18649

[services.development]
run = "pnpm --filter @workspace/streamflix run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/streamflix", "run", "build" ]
serve = "static"
publicDir = "artifacts/streamflix/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18649"
BASE_PATH = "/"
